cursor #eddfe4
cursor_text_color #d3c2c9

foreground            #eddfe4
background            #181115
selection_foreground  #3f2a36
selection_background  #debece
url_color             #f9b1db

color0   #181115
color1   #ff727c
color2   #9ef97c
color3   #ffe072
color4   #ec9aca
color5   #733659
color6   #f9b1db
color7   #ffeff8
color8   #a1959c
color9   #ff9fa6
color10  #beffa5
color11  #ffeba5
color12  #ffc0e4
color13  #ffcbe9
color14  #ffddf1
color15  #fff8fc
