-- Atomic: retro space-age colorscheme for Neovim

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "atomic"
vim.o.termguicolors = true

local c = {
  bg         = "#162830",
  bg_surface = "#1e3038",
  bg_border  = "#2a3d44",
  bg_hl      = "#354a52",
  fg         = "#f5ecd7",
  fg_dim     = "#d9cdb8",
  fg_muted   = "#8a7d6b",
  orange     = "#e05a2d",
  teal       = "#2fb8b0",
  green      = "#4dcb8a",
  yellow     = "#e8c547",
  red        = "#c9392b",
  blue       = "#4a7fa5",
  purple     = "#7b68b0",
  pink       = "#c47a98",
  amber      = "#d4953a",
  none       = "NONE",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hi("Normal",        { fg = c.fg, bg = c.bg })
hi("NormalFloat",   { fg = c.fg, bg = c.bg_surface })
hi("FloatBorder",   { fg = c.bg_border, bg = c.bg_surface })
hi("CursorLine",    { bg = c.bg_surface })
hi("CursorColumn",  { bg = c.bg_surface })
hi("ColorColumn",   { bg = c.bg_surface })
hi("Visual",        { bg = c.bg_hl })
hi("VisualNOS",     { bg = c.bg_hl })
hi("Search",        { fg = c.bg, bg = c.yellow })
hi("IncSearch",     { fg = c.bg, bg = c.orange })
hi("CurSearch",     { fg = c.bg, bg = c.orange })
hi("Substitute",    { fg = c.bg, bg = c.orange })
hi("LineNr",        { fg = c.fg_muted })
hi("CursorLineNr",  { fg = c.orange, bold = true })
hi("SignColumn",     { fg = c.fg_muted, bg = c.bg })
hi("FoldColumn",     { fg = c.fg_muted, bg = c.bg })
hi("Folded",         { fg = c.fg_dim, bg = c.bg_surface })
hi("VertSplit",      { fg = c.bg_border })
hi("WinSeparator",   { fg = c.bg_border })
hi("StatusLine",     { fg = c.fg_dim, bg = c.bg_surface })
hi("StatusLineNC",   { fg = c.fg_muted, bg = c.bg_surface })
hi("TabLine",        { fg = c.fg_muted, bg = c.bg_surface })
hi("TabLineFill",    { bg = c.bg_surface })
hi("TabLineSel",     { fg = c.fg, bg = c.bg, bold = true })
hi("WinBar",         { fg = c.fg_dim, bg = c.bg })
hi("WinBarNC",       { fg = c.fg_muted, bg = c.bg })
hi("Pmenu",          { fg = c.fg_dim, bg = c.bg_surface })
hi("PmenuSel",       { fg = c.fg, bg = c.bg_hl })
hi("PmenuSbar",      { bg = c.bg_border })
hi("PmenuThumb",     { bg = c.fg_muted })
hi("WildMenu",       { fg = c.bg, bg = c.orange })
hi("Directory",      { fg = c.teal })
hi("Title",          { fg = c.orange, bold = true })
hi("MatchParen",     { fg = c.orange, bold = true, underline = true })
hi("NonText",        { fg = c.bg_border })
hi("SpecialKey",     { fg = c.bg_border })
hi("Whitespace",     { fg = c.bg_border })
hi("EndOfBuffer",    { fg = c.bg })
hi("Conceal",        { fg = c.fg_muted })
hi("QuickFixLine",   { bg = c.bg_hl })
hi("ModeMsg",        { fg = c.fg_dim, bold = true })
hi("MoreMsg",        { fg = c.teal })
hi("Question",       { fg = c.teal })
hi("ErrorMsg",       { fg = c.red })
hi("WarningMsg",     { fg = c.yellow })
hi("DiffAdd",        { bg = "#1a3328" })
hi("DiffChange",     { bg = "#1a2a33" })
hi("DiffDelete",     { fg = c.red, bg = "#2a1a1a" })
hi("DiffText",       { bg = "#1e3545" })
hi("SpellBad",       { sp = c.red, undercurl = true })
hi("SpellCap",       { sp = c.yellow, undercurl = true })
hi("SpellLocal",     { sp = c.teal, undercurl = true })
hi("SpellRare",      { sp = c.purple, undercurl = true })

-- Syntax
hi("Comment",        { fg = c.fg_muted, italic = true })
hi("String",         { fg = c.green })
hi("Character",      { fg = c.green })
hi("Number",         { fg = c.amber })
hi("Float",          { fg = c.amber })
hi("Boolean",        { fg = c.amber })
hi("Identifier",     { fg = c.fg })
hi("Function",       { fg = c.teal })
hi("Statement",      { fg = c.orange })
hi("Conditional",    { fg = c.orange })
hi("Repeat",         { fg = c.orange })
hi("Label",          { fg = c.orange })
hi("Operator",       { fg = c.fg_dim })
hi("Keyword",        { fg = c.orange })
hi("Exception",      { fg = c.red })
hi("PreProc",        { fg = c.pink })
hi("Include",        { fg = c.pink })
hi("Define",         { fg = c.pink })
hi("Macro",          { fg = c.pink })
hi("PreCondit",      { fg = c.pink })
hi("Type",           { fg = c.yellow })
hi("StorageClass",   { fg = c.purple })
hi("Structure",      { fg = c.yellow })
hi("Typedef",        { fg = c.yellow })
hi("Special",        { fg = c.amber })
hi("SpecialChar",    { fg = c.amber })
hi("Tag",            { fg = c.teal })
hi("Delimiter",      { fg = c.fg_dim })
hi("SpecialComment", { fg = c.fg_muted, bold = true })
hi("Debug",          { fg = c.red })
hi("Underlined",     { underline = true })
hi("Error",          { fg = c.red })
hi("Todo",           { fg = c.bg, bg = c.yellow, bold = true })

-- Diagnostics
hi("DiagnosticError",          { fg = c.red })
hi("DiagnosticWarn",           { fg = c.yellow })
hi("DiagnosticInfo",           { fg = c.blue })
hi("DiagnosticHint",           { fg = c.teal })
hi("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hi("DiagnosticUnderlineWarn",  { sp = c.yellow, undercurl = true })
hi("DiagnosticUnderlineInfo",  { sp = c.blue, undercurl = true })
hi("DiagnosticUnderlineHint",  { sp = c.teal, undercurl = true })
hi("DiagnosticVirtualTextError", { fg = c.red, bg = "#1e1215" })
hi("DiagnosticVirtualTextWarn",  { fg = c.yellow, bg = "#1e1a12" })
hi("DiagnosticVirtualTextInfo",  { fg = c.blue, bg = "#121a1e" })
hi("DiagnosticVirtualTextHint",  { fg = c.teal, bg = "#121e1c" })

-- LSP
hi("LspReferenceText",  { bg = c.bg_hl })
hi("LspReferenceRead",  { bg = c.bg_hl })
hi("LspReferenceWrite", { bg = c.bg_hl, bold = true })
hi("LspSignatureActiveParameter", { fg = c.orange, bold = true })


-- Git signs
hi("GitSignsAdd",    { fg = c.green })
hi("GitSignsChange", { fg = c.blue })
hi("GitSignsDelete", { fg = c.red })

-- Treesitter
hi("@variable",           { fg = c.fg })
hi("@variable.builtin",   { fg = c.pink })
hi("@variable.parameter", { fg = c.fg_dim })
hi("@variable.member",    { fg = c.fg })
hi("@constant",           { fg = c.amber })
hi("@constant.builtin",   { fg = c.amber })
hi("@constant.macro",     { fg = c.amber })
hi("@module",             { fg = c.blue })
hi("@label",              { fg = c.orange })
hi("@string",             { fg = c.green })
hi("@string.escape",      { fg = c.amber })
hi("@string.regexp",      { fg = c.pink })
hi("@character",          { fg = c.green })
hi("@number",             { fg = c.amber })
hi("@boolean",            { fg = c.amber })
hi("@float",              { fg = c.amber })
hi("@function",           { fg = c.teal })
hi("@function.builtin",   { fg = c.teal, italic = true })
hi("@function.call",      { fg = c.teal })
hi("@function.macro",     { fg = c.pink })
hi("@function.method",    { fg = c.teal })
hi("@function.method.call", { fg = c.teal })
hi("@constructor",        { fg = c.yellow })
hi("@operator",           { fg = c.fg_dim })
hi("@keyword",            { fg = c.orange })
hi("@keyword.conditional", { fg = c.orange })
hi("@keyword.repeat",     { fg = c.orange })
hi("@keyword.return",     { fg = c.orange })
hi("@keyword.exception",  { fg = c.red })
hi("@keyword.import",     { fg = c.pink })
hi("@keyword.operator",   { fg = c.orange })
hi("@keyword.function",   { fg = c.orange })
hi("@keyword.modifier",   { fg = c.purple })
hi("@type",               { fg = c.yellow })
hi("@type.builtin",       { fg = c.yellow, italic = true })
hi("@type.qualifier",     { fg = c.orange })
hi("@attribute",          { fg = c.pink })
hi("@property",           { fg = c.fg })
hi("@comment",            { fg = c.fg_muted, italic = true })
hi("@comment.todo",       { fg = c.bg, bg = c.yellow, bold = true })
hi("@comment.note",       { fg = c.bg, bg = c.teal, bold = true })
hi("@comment.warning",    { fg = c.bg, bg = c.yellow, bold = true })
hi("@comment.error",      { fg = c.bg, bg = c.red, bold = true })
hi("@punctuation.bracket",   { fg = c.fg_dim })
hi("@punctuation.delimiter", { fg = c.fg_dim })
hi("@punctuation.special",   { fg = c.amber })
hi("@tag",                { fg = c.orange })
hi("@tag.attribute",      { fg = c.teal })
hi("@tag.delimiter",      { fg = c.fg_muted })
hi("@markup.heading",     { fg = c.orange, bold = true })
hi("@markup.strong",      { bold = true })
hi("@markup.italic",      { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.link",        { fg = c.teal, underline = true })
hi("@markup.link.url",    { fg = c.blue, underline = true })
hi("@markup.raw",         { fg = c.green })
hi("@markup.list",        { fg = c.orange })

-- Telescope
hi("TelescopeNormal",        { fg = c.fg_dim, bg = c.bg_surface })
hi("TelescopeBorder",        { fg = c.bg_border, bg = c.bg_surface })
hi("TelescopeTitle",         { fg = c.orange, bold = true })
hi("TelescopePromptNormal",  { fg = c.fg, bg = c.bg_surface })
hi("TelescopePromptBorder",  { fg = c.bg_border, bg = c.bg_surface })
hi("TelescopePromptTitle",   { fg = c.orange, bold = true })
hi("TelescopePromptPrefix",  { fg = c.orange })
hi("TelescopeResultsNormal", { fg = c.fg_dim, bg = c.bg_surface })
hi("TelescopeResultsBorder", { fg = c.bg_border, bg = c.bg_surface })
hi("TelescopePreviewNormal", { fg = c.fg_dim, bg = c.bg })
hi("TelescopePreviewBorder", { fg = c.bg_border, bg = c.bg })
hi("TelescopePreviewTitle",  { fg = c.teal, bold = true })
hi("TelescopeSelection",     { fg = c.fg, bg = c.bg_hl })
hi("TelescopeMatching",      { fg = c.orange, bold = true })

-- Indent blankline
hi("IblIndent", { fg = c.bg_border })
hi("IblScope",  { fg = c.bg_hl })
hi("IndentBlanklineChar",        { fg = c.bg_border })
hi("IndentBlanklineContextChar", { fg = c.bg_hl })

-- nvim-cmp
hi("CmpItemAbbr",           { fg = c.fg_dim })
hi("CmpItemAbbrMatch",      { fg = c.orange, bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = c.orange })
hi("CmpItemAbbrDeprecated", { fg = c.fg_muted, strikethrough = true })
hi("CmpItemKindDefault",    { fg = c.fg_muted })
hi("CmpItemKindFunction",   { fg = c.teal })
hi("CmpItemKindMethod",     { fg = c.teal })
hi("CmpItemKindVariable",   { fg = c.fg })
hi("CmpItemKindKeyword",    { fg = c.orange })
hi("CmpItemKindField",      { fg = c.fg })
hi("CmpItemKindProperty",   { fg = c.fg })
hi("CmpItemKindClass",      { fg = c.yellow })
hi("CmpItemKindStruct",     { fg = c.yellow })
hi("CmpItemKindInterface",  { fg = c.yellow })
hi("CmpItemKindModule",     { fg = c.blue })
hi("CmpItemKindSnippet",    { fg = c.pink })
hi("CmpItemKindText",       { fg = c.fg_dim })
hi("CmpItemKindConstant",   { fg = c.amber })
hi("CmpItemKindValue",      { fg = c.amber })
hi("CmpItemKindEnum",       { fg = c.yellow })
hi("CmpItemKindEnumMember", { fg = c.amber })
hi("CmpItemKindOperator",   { fg = c.fg_dim })
hi("CmpItemKindReference",  { fg = c.purple })
hi("CmpItemKindTypeParameter", { fg = c.yellow })

-- Notify
hi("NotifyERRORBorder", { fg = c.red })
hi("NotifyWARNBorder",  { fg = c.yellow })
hi("NotifyINFOBorder",  { fg = c.teal })
hi("NotifyDEBUGBorder", { fg = c.fg_muted })
hi("NotifyTRACEBorder", { fg = c.purple })
hi("NotifyERRORIcon",   { fg = c.red })
hi("NotifyWARNIcon",    { fg = c.yellow })
hi("NotifyINFOIcon",    { fg = c.teal })
hi("NotifyDEBUGIcon",   { fg = c.fg_muted })
hi("NotifyTRACEIcon",   { fg = c.purple })
hi("NotifyERRORTitle",  { fg = c.red })
hi("NotifyWARNTitle",   { fg = c.yellow })
hi("NotifyINFOTitle",   { fg = c.teal })
hi("NotifyDEBUGTitle",  { fg = c.fg_muted })
hi("NotifyTRACETitle",  { fg = c.purple })

-- Mini (LazyVim uses mini.indentscope, mini.bufremove, etc.)
hi("MiniIndentscopeSymbol", { fg = c.bg_hl })

-- Lazy.nvim
hi("LazyButton",       { fg = c.fg_dim, bg = c.bg_surface })
hi("LazyButtonActive",  { fg = c.fg, bg = c.bg_hl, bold = true })
hi("LazyH1",           { fg = c.bg, bg = c.orange, bold = true })
hi("LazySpecial",      { fg = c.teal })
hi("LazyProgressDone", { fg = c.orange })
hi("LazyProgressTodo", { fg = c.bg_border })

-- Which-key
hi("WhichKey",          { fg = c.orange })
hi("WhichKeyGroup",     { fg = c.teal })
hi("WhichKeyDesc",      { fg = c.fg_dim })
hi("WhichKeySeparator",  { fg = c.fg_muted })
hi("WhichKeyValue",     { fg = c.fg_muted })

-- Neo-tree
hi("NeoTreeNormal",       { fg = c.fg_dim, bg = c.bg_surface })
hi("NeoTreeNormalNC",     { fg = c.fg_dim, bg = c.bg_surface })
hi("NeoTreeDirectoryName", { fg = c.teal })
hi("NeoTreeDirectoryIcon", { fg = c.teal })
hi("NeoTreeRootName",     { fg = c.orange, bold = true })
hi("NeoTreeFileName",     { fg = c.fg_dim })
hi("NeoTreeGitModified",  { fg = c.blue })
hi("NeoTreeGitAdded",     { fg = c.green })
hi("NeoTreeGitDeleted",   { fg = c.red })
hi("NeoTreeGitUntracked", { fg = c.fg_muted })
hi("NeoTreeIndentMarker", { fg = c.bg_border })

-- Dashboard / Alpha
hi("DashboardHeader",   { fg = c.orange })
hi("DashboardFooter",   { fg = c.fg_muted, italic = true })
hi("DashboardShortCut", { fg = c.teal })
hi("DashboardKey",      { fg = c.orange })
hi("DashboardDesc",     { fg = c.fg_dim })
hi("DashboardIcon",     { fg = c.teal })
