# config.nu — interactive shell settings, aliases and custom commands.
#
# Loaded after env.nu. See `config nu --doc | nu-highlight | less -R` for the
# full list of options.

$env.config.show_banner = false
$env.config.edit_mode = "emacs"
$env.config.buffer_editor = "nvim"

$env.config.rm.always_trash = true

$env.config.ls.use_ls_colors = true

$env.config.table.mode = "rounded"
$env.config.table.index_mode = "auto"

$env.config.completions.algorithm = "fuzzy"
$env.config.completions.case_sensitive = false
$env.config.completions.partial = true
$env.config.completions.quick = true

$env.config.history.file_format = "sqlite"
$env.config.history.max_size = 1_000_000
$env.config.history.sync_on_enter = true
$env.config.history.isolation = true

# Let the terminal (ghostty/kitty) mark prompts and track the cwd.
$env.config.shell_integration.osc2 = true
$env.config.shell_integration.osc7 = true
$env.config.shell_integration.osc133 = true

# --------------------------------------------------------------- aliases ---

alias vim = nvim
alias nv = nvim

# ------------------------------------------------------- custom commands ---

# Phoenix/Elixir project helpers
def resg [] { mix setup }
def resgs [] { mix setup; mix run priv/repo/seeds_scale.exs }
def rung [] { mix phx.server }

# Prune remotes, delete merged & gone local branches.
def git-cleanup [--main-branch: string = "main"] {
    git fetch --prune

    let protected = ["main" "master" $main_branch]

    let merged = (
        git branch --merged $main_branch
        | lines
        | each { str replace -r '^\*?\s*' '' }
        | where { |b| $b not-in $protected }
    )

    let gone = (
        git branch -vv
        | lines
        | where { |l| $l =~ ': gone\]' }
        | each { |l| $l | str replace -r '^\*?\s*' '' | split row -r '\s+' | first }
        | where { |b| $b not-in $protected }
    )

    for branch in ($merged | append $gone | uniq) {
        git branch -d $branch
    }
}

# ------------------------------------------------------------ completions ---

# jj, generated by env.nu.
use ~/.cache/nushell/completions-jj.nu *

# ---------------------------------------------------------------- prompt ---

# starship, configured in ../starship.toml; generated by env.nu.
source ~/.cache/nushell/starship.nu
