return {
  -- {'kezhenxu94/vim-mysql-plugin'},
  -- {
  --   "kndndrj/nvim-dbee",
  --   dependencies = {
  --     "MunifTanjim/nui.nvim",
  --   },
  --   build = function()
  --     -- Install tries to automatically detect the install method.
  --     -- if it fails, try calling it with one of these parameters:
  --     --    "curl", "wget", "bitsadmin", "go"
  --     require("dbee").install()
  --   end,
  --   config = function()
  --
  --     local dbeeSetupParams = {
  --       connections = {
  --       }
  --     }
  --     -- pcall(require, 'code-dap-local')
  --     require('local-db-connections')(dbeeSetupParams)
  --     require("dbee").setup(dbeeSetupParams)
  --   end,
  -- },
  -- {'tpope/vim-dadbod'},
  -- {'kristijanhusak/vim-dadbod-ui', config = function()
  --   local dbs = {
  --     -- { name = "client_db", url = "mysql://user:pass@localhost/client_db" }
  --   }
  --   local success, localDbs = pcall(require, 'local-db-connections')
  --   if success then localDbs(dbs) else print("no local-db-connections") end
  --   vim.g.dbs = dbs;
  -- end
  -- }
}

-- Example content for local-db-connections
-- return function (dbs)
--   table.insert(dbs, { name = "client_db", url = "mysql://user:pass@localhost/client_db" })
--   -- repeat as needed, one table.insert() per connection.
-- end
