[colors]
background = '#131318'
foreground = '#e4e1e9'

cursor_bg = '#c1c1ff'
cursor_fg = '#131318'
cursor_border = '#c1c1ff'

selection_bg = '#414178'
selection_fg = '#e4e1e9'

ansi = ['#131318', '#ff7294', '#7fff96', '#ffd872', '#ababf2', '#414176', '#c1c1ff', '#efefff']
brights = ['#9999a5', '#ff9fb6', '#a5ffb5', '#ffe6a5', '#cacaff', '#d3d3ff', '#e3e3ff', '#f8f8ff']
