[colors]
background = '#1a110f'
foreground = '#f1dfda'

cursor_bg = '#ffb4a2'
cursor_fg = '#1a110f'
cursor_border = '#ffb4a2'

selection_bg = '#723425'
selection_fg = '#f1dfda'

ansi = ['#1a110f', '#ff7672', '#98ff7f', '#ffe472', '#f29c88', '#763627', '#ffb4a2', '#fff2ef']
brights = ['#a59b99', '#ffa19f', '#b7ffa5', '#ffeea5', '#ffbfaf', '#ffcabd', '#ffddd5', '#fff9f8']
