[colors]
background = '#181115'
foreground = '#eddfe4'

cursor_bg = '#f9b1db'
cursor_fg = '#181115'
cursor_border = '#f9b1db'

selection_bg = '#6a3457'
selection_fg = '#eddfe4'

ansi = ['#181115', '#ff727c', '#9ef97c', '#ffe072', '#ec9aca', '#733659', '#f9b1db', '#ffeff8']
brights = ['#a1959c', '#ff9fa6', '#beffa5', '#ffeba5', '#ffc0e4', '#ffcbe9', '#ffddf1', '#fff8fc']
